### ISSUE TITLE
Middleware are not executing in the expected order

### ISSUE THREAD

**Issue by tatang26** [leapkit/leapkit#2]
When a middleware list is set by using the `r.Use()` method, the middleware execution order is not the expected.

```go
mws := []server.Middleware{ mw1, mw2, mw3 }

func main() {
	server := server.New()
	server.Use(mws...)
}
```

**Expected** 
`mw1 -> mw2 -> mw3`

**Current**
`mw3 -> mw2 -> mw1`

**Comment by paganotoni** [comment]
Thank you @tatang26. Covered in #3
