### ISSUE TITLE
GUI choices

### ISSUE THREAD

**Issue by gedw99** [leapkit/leapkit#27]
https://shoelace.style is one that many golang devs are using. 

Wondering where we should add components to Leap kit ? If you dont want it here let me know :)

https://github.com/paganotoni/todox/blob/main/internal/todos/index.go uses github.com/delaneyj/gostar/elements, and that works and give you full control, but also he has also switched to shoelace.style

**Comment by paganotoni** [comment]
This is a good topic @gedw99! Shoelace can just be added to the template. As for the components I have been thinking about providing an interface so developers can use their own renderer. Both, components and shoelace can be added after the base leapkit template has been generated.
